### ISSUE TITLE
`re` step runs significantly slower compared against an earlier version

### ISSUE THREAD

**Issue by liangyuRain** [microsoft/msccl#28]
Hi, I have tested the following reduce-scatter schedule and observed a significantly larger runtime at large sizes compared against an earlier commit.

[schedule.txt](https://github.com/microsoft/msccl/files/9081103/schedule.txt)

Runtimes at size 134217728 bytes:
- `cbe70894b4da45fca99539269c857a6afb0a21a3 (origin/master)`: 16967us
- `e52c5259b6a9ee34b9c8bb0ff8f8d18b4b6cbe00`: 2916.2us

Both runs succeed in datacheck.

After some debugging, it seems that the `re` step somehow runs significantly slower since commit `179f5f995807e870c3dc99aba76502bf737e5d86`. Especially, I have tried the following schedule at several commits:
```XML
<algo name="test" proto="Simple" nchannels="1" nchunksperloop="8" ngpus="2" coll="allreduce" inplace="1">
  <gpu id="0" i_chunks="16" o_chunks="0" s_chunks="0">
    <tb id="0" send="-1" recv="-1" chan="0">
      <step s="0" type="re" srcbuf="i" srcoff="0" dstbuf="i" dstoff="8" cnt="8" depid="-1" deps="-1" hasdep="0"/>
    </tb>
  </gpu>
  <gpu id="1" i_chunks="8" o_chunks="0" s_chunks="0">
  </gpu>
</algo>
```
Runtimes at size 150994944 bytes:
- `cbe70894b4da45fca99539269c857a6afb0a21a3 (origin/master)`: 17677us
- `179f5f995807e870c3dc99aba76502bf737e5d86`: 29189us
- `35a1d4b8da248ce97c8924745d897aae5c79eecc (tag: v0.6.2)`: 2624.8us
- `e52c5259b6a9ee34b9c8bb0ff8f8d18b4b6cbe00`: 2621.7us

**Comment by saeedmaleki** [comment]
Hi @liangyuRain,

I merged most of `ll_load_al_fix` into master except for the volatile loads in `LL` protocol which causes incorrect results for very small sizes. So, master now has the performant runtime without the `LL` fix. We are working on upgrading the runtime to latest NCCL (2.12) which is in this [branch](https://github.com/microsoft/msccl/tree/merging_with_nccl). I will fix the load issue for `LL` in that branch and merge everything into master.

For now, I reopened the `LL` issue and I will keep `ll_load_al_fix` alive if you want the "hot" fix for the correctness issue.

Summary:
- `master`: based on NCCL 2.8.4 with most bugs fixed except for `re` operations with `LL` protocol. This version is performant yet incorrect.
- `ll_load_al_fix`: based on NCCL 2.8.4 with all bugs fixed but `re` operation has huge performance implications.
- `merging_with_nccl`: based on NCCL 2.12. Still in progress but will have a performant fix for `LL` `re` operation.

Makes sense?

**Comment by liangyuRain** [comment]
Hi @saeedmaleki, thank you for all the bug fixes. That totally makes sense. Meanwhile, do you have a timeline for when this slow `re` will be fixed? It causes a huge problem for the experiments we are currently doing.

**Comment by liangyuRain** [comment]
Hi @saeedmaleki, I have tried `reduction_in_prims` branch. The `schedule.txt` indeed runs faster, but the runtime 6003.3us is still twice the runtime of commit `e52c5259b6a9ee34b9c8bb0ff8f8d18b4b6cbe00` 2916.2us at size 134217720. The simple `re` schedule does not run properly in the branch. It finishes with 0.61us.

I have open another [issue](https://github.com/microsoft/msccl/issues/30) with branch `reduction_in_prims`.

**Comment by saeedmaleki** [comment]
pull. I see 2467us on two A100s now.
