### ISSUE TITLE
nvlink errors when building msccl

### ISSUE THREAD

**Issue by de1star** [microsoft/msccl#34]
I got lots of nvlink errors when building msccl:   
![image](https://user-images.githubusercontent.com/37529028/179462214-a4eaabf9-bc8d-4be9-8f40-df5144889c4c.png)
Could please you help me with that?

**Comment by saeedmaleki** [comment]
hi, can you please give us your steps for building MSCCL? What CUDA version have you used?

**Comment by de1star** [comment]
Hi, I cloned the repo and tried again, but I still got nvlink errors. This time I set VERBOSE as 1 and I found here is a 'Permission denied'.   
![image](https://user-images.githubusercontent.com/37529028/179654144-2c6536d4-3ac7-4a71-9c5d-286470fbc5b3.png)
I am not sure whether it's the reason leading to nvlink errors...

**Comment by saeedmaleki** [comment]
That could be a good reason for it. Can you please try changing the permission on it?
Another idea would be to rm the msccl folder entirely and git clone a fresh copy and retry. Sometimes the file permissions get messed up.

**Comment by de1star** [comment]
Hi, I solved this problem by using 'chmod +x msccl/src/collectives/device/gen_rules.sh', and 'Permission denied' did not appear now.

**Comment by de1star** [comment]
Also I got another error at first:   
![image](https://user-images.githubusercontent.com/37529028/179666729-6f24f25d-ab4d-4b5e-8021-3180fc3aa988.png)
I modified the code:   
![image](https://user-images.githubusercontent.com/37529028/179666826-5e4d39cf-2e2f-4b03-988d-a91dac6a931e.png)

**Comment by saeedmaleki** [comment]
Fantastic! Great find on the last error. Can you please raise a PR for it?

**Comment by de1star** [comment]
Hi, I have raised a PR, but I am not sure whether the assertion error information is clearly enough for other users, modify it if you have any suggestions.

**Comment by saeedmaleki** [comment]
Looked good, I merged it. Thanks for your contribution!
