### ISSUE TITLE
Performance of msccl did not improve compared with nccl

### ISSUE THREAD

**Issue by de1star** [microsoft/msccl#36]
Hi, I just ran nccl-tests on 2 nodes with 8 nvlinked A100s on each of them by using the test.xml built by ‘python msccl-tools/examples/mscclang/allreduce_a100_allpairs.py --protocol=LL 16 4 > test.xml’, and I set NCCL_DEBUG as INFO to make sure I have connected nccl with msccl algorithms by 'NCCL INFO Connected 1 MSCCL algorithms'. I got this nccl-tests result:   
![image](https://user-images.githubusercontent.com/37529028/179717504-2029ea9b-a65d-4ca5-8500-de24d872877a.png)
I found in-place results became much slower than out-of-place results when the data size was larger. Could you help me with that?

**Comment by de1star** [comment]
I used 2 nodes with 8 nvlinked A100s on each of them.

**Comment by saeedmaleki** [comment]
Yes! The idea behind MSCCL is to hyper-optimize a collective for a given topology and a tensor size. From your out-of-place numbers, I can only guess that your system has only one IB per node with 200Gbps bandwidth (please correct me if I am wrong). In the allpair algorithm, each pair of GPU make a connection. This means that your IB is make 8x8=64 connections each way which severely hurst performance. Also note that you are using ` --proto=LL 16 4` as your arguments which means that the number of connections is multiplied by 4 (256 IB connections).  You could write your own AllReduce algorithm for your system using our MSCCL language. I would imagine a [hierarchical](https://github.com/microsoft/msccl-tools/blob/main/examples/mscclang/hierarchical_allreduce.py) AllReduce would perform significantly better, but you need to adjust the algorithm as the linked one assumes that there are 8 IBs per node.

Please refer to this [paper](https://arxiv.org/pdf/2201.11840.pdf) for more details.

**Comment by de1star** [comment]
Thank you a lot for your reply! I changed --proto=LL 16 4 as --proto=LL 16 16, then found the speed of in-place and out-of-place became almost the same, so I thought maybe I did not take a full use of my system. But I got your idea that the allpair algorithm might not be the best solution for my system. I will have a try on my own custom AllReduce algorithm after reading the paper carefully!

**Comment by de1star** [comment]
Oh, got it. Thank you!
