### ISSUE TITLE
Interesting dip in runtime

### ISSUE THREAD

**Issue by liangyuRain** [microsoft/msccl#41]
Hi, we have observed an interesting phenomenon with multi-channel/multi-instance schedules. When experimenting the schedules with different sizes, we observed a short dip in runtime around 1MB as size increases. The phenomenon has been observed across almost all schedules. We wonder if there is an explanation for this.

The following plot shows the phenomenon from 8-node ring allreduce schedules with `Simple` protocol:
![7a94804b-bd9d-4f16-8bfb-3fa39c060c64](https://user-images.githubusercontent.com/33206816/181876582-6a882701-d11a-49ad-b6a9-7ca00e083095.png)

The `LL` has a similar but less significant dip:
![cccd949a-64f9-43e4-8f33-beb818529bbd](https://user-images.githubusercontent.com/33206816/181876594-1c1cb425-c0d5-44e6-9000-04894c87e072.png)

The above results are obtained from our testbed. We are also able to reproduce this dip on NVSwitch system:

`AR_OptNaiveBiRing_2_8_n8_c8_tb16_cf1_Simple_v2.xml`:
```
#
#                                                       out-of-place                       in-place          
#       size         count      type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                       (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
         512           128     float     sum    169.8    0.00    0.01  1e-07
        1024           256     float     sum    170.3    0.01    0.01  2e-07
        2048           512     float     sum    165.9    0.01    0.02  2e-07
        4096          1024     float     sum    159.7    0.03    0.04  2e-07
        8192          2048     float     sum    154.1    0.05    0.09  2e-07
       16384          4096     float     sum    154.3    0.11    0.19  2e-07
       32768          8192     float     sum    153.7    0.21    0.37  2e-07
       65536         16384     float     sum    150.2    0.44    0.76  2e-07
      131072         32768     float     sum    144.6    0.91    1.59  2e-07
      262144         65536     float     sum    145.7    1.80    3.15  2e-07
      524288        131072     float     sum    153.4    3.42    5.98  2e-07
     1048576        262144     float     sum    155.5    6.74   11.80  2e-07
     2097152        524288     float     sum    161.4   13.00   22.74  2e-07
     4194304       1048576     float     sum    173.6   24.15   42.27  2e-07
     8388608       2097152     float     sum    193.3   43.40   75.95  2e-07
    16777216       4194304     float     sum    235.2   71.35  124.85  2e-07
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 18.1146 
#
```

`AR_OptNaiveBiRing_2_8_n8_c4_tb8_cf1_Simple_v2.xml`:
```
#
#                                                       out-of-place                       in-place          
#       size         count      type   redop     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)                       (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
         256            64     float     sum    156.2    0.00    0.00  1e-07
         512           128     float     sum    156.1    0.00    0.01  1e-07
        1024           256     float     sum    153.7    0.01    0.01  2e-07
        2048           512     float     sum    147.4    0.01    0.02  2e-07
        4096          1024     float     sum    145.6    0.03    0.05  2e-07
        8192          2048     float     sum    135.9    0.06    0.11  2e-07
       16384          4096     float     sum    129.0    0.13    0.22  2e-07
       32768          8192     float     sum    127.8    0.26    0.45  2e-07
       65536         16384     float     sum    126.7    0.52    0.91  2e-07
      131072         32768     float     sum    126.7    1.03    1.81  2e-07
      262144         65536     float     sum    134.6    1.95    3.41  2e-07
      524288        131072     float     sum    136.6    3.84    6.72  2e-07
     1048576        262144     float     sum    141.5    7.41   12.97  2e-07
     2097152        524288     float     sum    154.6   13.57   23.74  2e-07
     4194304       1048576     float     sum    171.3   24.48   42.84  2e-07
     8388608       2097152     float     sum    224.2   37.41   65.47  2e-07
    16777216       4194304     float     sum    315.0   53.26   93.20  2e-07
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 14.8194 
#
```

The schedules are attached:
- 1 channel: [AR_OptNaiveBiRing_2_8_n8_c1_tb2_cf1_Simple_v2.txt](https://github.com/microsoft/msccl/files/9225416/AR_OptNaiveBiRing_2_8_n8_c1_tb2_cf1_Simple_v2.txt)
- 2 channel: [AR_OptNaiveBiRing_2_8_n8_c2_tb4_cf1_Simple_v2.txt](https://github.com/microsoft/msccl/files/9225418/AR_OptNaiveBiRing_2_8_n8_c2_tb4_cf1_Simple_v2.txt)
- 4 channel: [AR_OptNaiveBiRing_2_8_n8_c4_tb8_cf1_Simple_v2.txt](https://github.com/microsoft/msccl/files/9225419/AR_OptNaiveBiRing_2_8_n8_c4_tb8_cf1_Simple_v2.txt)
- 8 channel: [AR_OptNaiveBiRing_2_8_n8_c8_tb16_cf1_Simple_v2.txt](https://github.com/microsoft/msccl/files/9225421/AR_OptNaiveBiRing_2_8_n8_c8_tb16_cf1_Simple_v2.txt)

Could you also reproduce this phenomenon with your multi-channel/multi-instance schedules?

**Comment by saeedmaleki** [comment]
Hi @liangyuRain, the reason is because of unrolling effects. You can follow the logic in [here](https://github.com/microsoft/msccl/blob/0293f3786cad0d29c88592019182ae4fa6f83c8a/src/collectives/device/common_kernel.h#L658) and [here](https://github.com/microsoft/msccl/blob/0293f3786cad0d29c88592019182ae4fa6f83c8a/src/collectives/device/common_kernel.h#L669). I checked your `AR_OptNaiveBiRing_2_8_n8_c4_tb8_cf1_Simple_v2.xml` schedule. For anything less than 512KB, it has to go over both loops while for 512KB and 1MB it only runs the first loop and returns [here](https://github.com/microsoft/msccl/blob/0293f3786cad0d29c88592019182ae4fa6f83c8a/src/collectives/device/common_kernel.h#L662). Potentially you could find an optimal `UNROLL` factor for each size but that could easily make the code size several times larger. Or we could make a specific CUDA kernel for a given size. This is something we are working on, but it is not ready yet.

**Comment by saeedmaleki** [comment]
did it answer your question @liangyuRain?

**Comment by liangyuRain** [comment]
Yes it has answered my question. Thx!
