### ISSUE TITLE
All-to-all correctness check does not seem to work

### ISSUE THREAD

**Issue by liangyuRain** [microsoft/msccl#50]
The all-to-all correctness check seems to pass on any schedule. Even ones that are intentionally modified to be wrong. It is possible that the schedule got ignored, but I have set `-x NCCL_DEBUG=WARN` and saw nothing.

The command I ran is as follows:
`mpirun -np 8 -x NCCL_NET_SHARED_BUFFERS=0  -x MSCCL_XML_FILES=schedule/allpairs_alltoall.xml -x NCCL_ALGO=MSCCL -x CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 -x NCCL_DEBUG=WARN -x NCCL_DEBUG_SUBSYS=ALL -x LD_LIBRARY_PATH=~/msccl/build/lib/:$LD_LIBRARY_PATH ~/nccl-tests/build/alltoall_perf -b 32 -e 16777216 -f 2 -g 1 -c 1 -n 200 -w 200 -z 0`

I am using the latest msccl and nccl-tests.

**Comment by saeedmaleki** [comment]
Hi @liangyuRain, please see this and let me know if it addresses your question. 

https://github.com/microsoft/msccl/issues/48

**Comment by liangyuRain** [comment]
Yes, this works perfectly. Thx!
