### ISSUE TITLE
nccl baseline

### ISSUE THREAD

**Issue by hongbilu** [microsoft/msccl#51]
which nccl version does msccl use as baseline?

**Comment by oliverYoung2001** [comment]
2.7.8-1 in SCCL, 
2.8.4-1 in GC3 and TACCL

**Comment by saeedmaleki** [comment]
The main branch is based on NCCL 2.12.12 and soon will be updated to 2.17.

**Comment by TonyWu199** [comment]
Looking forward to getting the updated msccl
