### ISSUE TITLE
How to set the target buffer size range for MSCCL algorithms

### ISSUE THREAD

**Issue by rashidi1saeed** [microsoft/msccl#54]
Hi, 
When I am writing MSCCL All-Reduce algorithms and run nccltest, it seems that for all-reduces greater than 64 MB, the MSCCL runtime falls back to the NCLL algorithm, rather than executing my MSCCL algorithm. How can we determine the buffer size range for our MSCCL algorithms?

Thanks

**Comment by saeedmaleki** [comment]
Hi Saeed,

For each XML, there are two attributes you can set for the head XML node: `minBytes` and `maxBytes` which define the range in which the algorithm would be selected. `maxBytes` by default, I believe, is 128MB. So, you can overwrite it by setting a larger value.

**Comment by rashidi1saeed** [comment]
Hi @saeedmaleki ,
Thanks for the reply! My problem got solved.
