### ISSUE TITLE
What is the difference between microsoft/msccl and Azure/msccl-executor-nccl?

### ISSUE THREAD

**Issue by jammycc** [microsoft/msccl#59]
What is the difference between this code repo and Azure's msccl-executor-nccl (https://github.com/Azure/msccl-executor-nccl )?
Both can be utilized for executing customized MSCCL algorithms, yet it appears that the NCCL baseline version employed by Azure's msccl-executor-nccl is 2.18, more recent than that used in this repo.

**Comment by yzygitzh** [comment]
Hi, https://github.com/Azure/msccl-executor-nccl is part of Azure MSCCL product (see https://github.com/Azure/msccl for full project introduction) that is being actively developed and maintained by Azure team, while this repo is the research prototype of Azure MSCCL product.

@saeedmaleki may have more comments.

**Comment by saeedmaleki** [comment]
yup, `Azure/msccl-executor-nccl` is the most up-to-date version and it is much faster than this repo. Please use `Azure/msccl-executor-nccl` for a long-run support of the project.

**Comment by jammycc** [comment]
I understand, thank you!
