### ISSUE TITLE
How to use test.xml algo.?

### ISSUE THREAD

**Issue by azharlightelligence** [microsoft/msccl#60]
Hi, I have successfully setup the msccl-tools and I can generate the .xml algo files from the examples as [described here](https://github.com/microsoft/msccl). Another question is how to use the synthesized .json [files here](https://github.com/microsoft/msccl-tools/blob/main/SYNTHESIS.md)

`python msccl-tools/examples/mscclang/allreduce_a100_allpairs.py --protocol=LL 8 2 > test.xml`. My quick question is 
how to enforce the usage of text.xml in the 

or `python msccl-tools/examples/mscclang/allreduce_a100_ring.py --protocol=Simple 8 1 1 > test.xml`
and copying the text.xml to `/msccl/executor/msccl-executor-nccl/build/lib/msccl-algorithms`

```
mpirun -np 1 -x LD_LIBRARY_PATH=msccl/exector/msccl-executor-nccl/build/lib/:$LD_LIBRARY_PATH -x NCCL_DEBUG=INFO -x NCCL_ALGO=TREE -x NCCL_DEBUG_SUBSYS=INIT,ENV msccl/tests/msccl-tests-nccl/build/all_reduce_perf -b 128 -e 32MB -f 2 -g 8 -c 1 -n 100 -w 100 -G 100 -z 0
```
Because it seems to ignore it and falling back to nccl. Thanks in advance for your help. Following is the topology I used with 8xA100 GPUs and 1 node

 ```
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7CPU Affinity    NUMA Affinity
GPU0     X      NV12    NV12    NV12    NV12    NV12    NV12    NV120-31    0
GPU1    NV12     X      NV12    NV12    NV12    NV12    NV12    NV120-31    0
GPU2    NV12    NV12     X      NV12    NV12    NV12    NV12    NV120-31    0
GPU3    NV12    NV12    NV12     X      NV12    NV12    NV12    NV120-31    0
GPU4    NV12    NV12    NV12    NV12     X      NV12    NV12    NV1232-63   1
GPU5    NV12    NV12    NV12    NV12    NV12     X      NV12    NV1232-63   1
GPU6    NV12    NV12    NV12    NV12    NV12    NV12     X      NV1232-63   1
GPU7    NV12    NV12    NV12    NV12    NV12    NV12    NV12     X 32-63    1

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

The issue is no matter what test.xml I used I get the same in-place and out-of-place results:

```
#
#                                                              out-of-place                       in-place          
#       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
#        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
         128            32     float     sum      -1    19.96    0.01    0.01      0    17.59    0.01    0.01      0
         256            64     float     sum      -1    17.75    0.01    0.03      0    17.78    0.01    0.03      0
         512           128     float     sum      -1    18.58    0.03    0.05      0    18.61    0.03    0.05      0
        1024           256     float     sum      -1    18.88    0.05    0.09      0    18.86    0.05    0.10      0
        2048           512     float     sum      -1    19.63    0.10    0.18      0    19.57    0.10    0.18      0
        4096          1024     float     sum      -1    21.03    0.19    0.34      0    21.01    0.19    0.34      0
        8192          2048     float     sum      -1    21.98    0.37    0.65      0    22.02    0.37    0.65      0
       16384          4096     float     sum      -1    22.44    0.73    1.28      0    22.48    0.73    1.28      0
       32768          8192     float     sum      -1    23.17    1.41    2.47      0    23.13    1.42    2.48      0
       65536         16384     float     sum      -1    24.22    2.71    4.74      0    24.14    2.72    4.75      0
      131072         32768     float     sum      -1    28.36    4.62    8.09      0    27.79    4.72    8.25      0
      262144         65536     float     sum      -1    44.06    5.95   10.41      0    43.96    5.96   10.44      0
      524288        131072     float     sum      -1    51.40   10.20   17.85      0    51.30   10.22   17.88      0
     1048576        262144     float     sum      -1    60.20   17.42   30.48      0    60.16   17.43   30.50      0
     2097152        524288     float     sum      -1    73.98   28.35   49.61      0    73.65   28.48   49.83      0
     4194304       1048576     float     sum      -1    100.2   41.86   73.25      0    99.04   42.35   74.11      0
     8388608       2097152     float     sum      -1    151.0   55.56   97.23      0    148.8   56.38   98.66      0
    16777216       4194304     float     sum      -1    254.9   65.81  115.16      0    254.6   65.89  115.31      0
    33554432       8388608     float     sum      -1    464.5   72.24  126.43      0    464.7   72.20  126.36      0

# Out of bounds values : 0 OK
# Avg bus bandwidth    : 28.4095 
```

I have doubled checked even if we remove the text.xml, the INFO log still prints CCL INFO NCCL_ALGO set by environment to msccl/executor/msccl-executor-nccl/build/lib/msccl-algorithms/test.xml.

**Comment by saeedmaleki** [comment]
hi @azharlightelligence 

Can you please give me your NCCL log? `NCCL_DEBUG=INFO`

You could also run with multiple process and see if it makes a difference:

```
mpirun -np 8 -x LD_LIBRARY_PATH=msccl/exector/msccl-executor-nccl/build/lib/:$LD_LIBRARY_PATH -x NCCL_DEBUG=INFO -x NCCL_ALGO=TREE -x NCCL_DEBUG_SUBSYS=INIT,ENV msccl/tests/msccl-tests-nccl/build/all_reduce_perf -b 128 -e 32MB -f 2 -g 1 -c 1 -n 100 -w 100 -G 100 -z 0
```

**Comment by azharlightelligence** [comment]
> hi @azharlightelligence
> 
> Can you please give me your NCCL log? `NCCL_DEBUG=INFO`
> 
> You could also run with multiple process and see if it makes a difference:
> 
> ```
> mpirun -np 8 -x LD_LIBRARY_PATH=msccl/exector/msccl-executor-nccl/build/lib/:$LD_LIBRARY_PATH -x NCCL_DEBUG=INFO -x NCCL_ALGO=TREE -x NCCL_DEBUG_SUBSYS=INIT,ENV msccl/tests/msccl-tests-nccl/build/all_reduce_perf -b 128 -e 32MB -f 2 -g 1 -c 1 -n 100 -w 100 -G 100 -z 0
> ```

Thanks for the feedback. I have logged as per your suggestion. Please find the attached log files
[out_without_xml.log](https://github.com/microsoft/msccl/files/13807107/out_without_xml.log)
[out_with_allreduce_a100_allpairs.py_protocol=Simple_8_1_xml 1.log](https://github.com/microsoft/msccl/files/13807108/out_with_allreduce_a100_allpairs.py_protocol.Simple_8_1_xml.1.log)

1) The `out_without_xml.log` is when no .xml file was there in `msccl/executor/msccl-executor-nccl/build/lib/msccl-algorithms`

2) The out_with_allreduce_a100_allpairs.py_protocol.Simple_8_1_xml.1.log is when text.xml is generated and put in this path `msccl/executor/msccl-executor-nccl/build/lib/msccl-algorithms`

The command to generate the `text.xml` is below
`python msccl-tools/examples/mscclang/allreduce_a100_allpairs.py --protocol=Simple 8 1  > test.xml`

**Comment by saeedmaleki** [comment]
Oh I see, you are using the new version of MSCCL. Please ask this question in [here](https://github.com/Azure/msccl). Others will be able to help you better.

**Comment by azharlightelligence** [comment]
> Contributor

Thanks for the feedback the issue is resolved in the suggested link
